name: mds_widget_book
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  widgetbook: ^3.7.0
  widgetbook_annotation: ^3.1.0

  majestica_ds:
    git:
      url: https://github.com/Majestica-Dev/design-system.git
      ref: main

  flutter_lints: ^3.0.1
  equatable: ^2.0.5
  number_text_input_formatter: ^1.0.0+7
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
